### ISSUE TITLE
[Bug Report] 'HumanRendering' object has no attribute 'window'

### ISSUE THREAD

**Issue by RogerJL** [Farama-Foundation/Gymnasium#1078]
### Describe the bug

This happens because self.window is set after asserts that causes close() method to be called
First seen [build-all 3.8](https://github.com/RogerJL/Gymnasium/actions/runs/9397642543/job/25881280360)

test_human_rendering.py::test_render_modes Exception ignored in: <function VectorEnv.__del__ at 0x00000211B439C9A0>
Traceback (most recent call last):
  File "C:\Users\roger\GITs\Gymnasium\gymnasium\vector\vector_env.py", line 324, in __del__
  File "C:\Users\roger\GITs\Gymnasium\gymnasium\wrappers\vector\rendering.py", line 178, in close
AttributeError: 'HumanRendering' object has no attribute 'window'

### System info

1.0.0a2
Windows 11
Python 3.11.9 (issue first seen on 3.8)

### Additional context

Patch on its way

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by RogerJL** [comment]
Issue can be seen here on main

https://github.com/Farama-Foundation/Gymnasium/actions/runs/9422643271/job/25959372466
```
tests/wrappers/vector/test_human_rendering.py::test_render_modes
  /usr/local/lib/python3.12/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function VectorEnv.__del__ at 0x7f7f7083f9c0>
  
  Traceback (most recent call last):
    File "/usr/local/gymnasium/gymnasium/vector/vector_env.py", line 324, in __del__
      self.close()
    File "/usr/local/gymnasium/gymnasium/wrappers/vector/rendering.py", line 178, in close
      if self.window is not None:
         ^^^^^^^^^^^
  AttributeError: 'HumanRendering' object has no attribute 'window'
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```
