### ISSUE TITLE
[Bug Report] Unable to play CarRacing-V2 due to assertion failure with keyset

### ISSUE THREAD

**Issue by kuds** [Farama-Foundation/Gymnasium#1096]
### Describe the bug

Unable to play CarRacing-V2 due to assertion failure with keyset

### Code example

```shell
import gymnasium as gym
from gymnasium.utils.play import play
play(gym.make("CarRacing-v2", render_mode="rgb_array"), keys_to_action={  
                                               "w": np.array([0, 0.7, 0]),
                                               "a": np.array([-1, 0, 0]),
                                               "s": np.array([0, 0, 1]),
                                               "d": np.array([1, 0, 0]),
                                               "wa": np.array([-1, 0.7, 0]),
                                               "dw": np.array([1, 0.7, 0]),
                                               "ds": np.array([1, 0, 1]),
                                               "as": np.array([-1, 0, 1]),
                                              }, noop=np.array([0,0,0]))
```

### System info

MacOS Sonoma 14.5
Gymnasium 0.29.0, 0.29.1, 1.0.0a2

### Additional context

When trying to execute the play example for CarRacing-V2 ([link](https://gymnasium.farama.org/api/utils/#gymnasium.utils.play.play)) in the documentation, it fails because of "assert action in env.action_space" exception. I have found that commenting out line 266 allows me to execute CarRacing-V2, but I do not believe that is a desired solution. If this truly an issue, I would be interested in fixing it but might need some direction. 

```shell
Traceback (most recent call last):
  File ".../PycharmProjects/Gymnasium/run.py", line 6, in <module>
    play(gym.make("CarRacing-v2", render_mode="rgb_array"), keys_to_action={
  File ".../PycharmProjects/Gymnasium/gymnasium/utils/play.py", line 266, in play
    assert action in env.action_space
AssertionError
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for reporting the issue, it is probably related to NumPy 2.0

You should just need to 
```python
import gymnasium as gym
import numpy as np

from gymnasium.utils.play import play

play(
    gym.make("CarRacing-v2", render_mode="rgb_array"),
    keys_to_action={
        "w": np.array([0, 0.7, 0], dtype=np.float32),
        "a": np.array([-1, 0, 0], dtype=np.float32),
        "s": np.array([0, 0, 1], dtype=np.float32),
        "d": np.array([1, 0, 0], dtype=np.float32),
        "wa": np.array([-1, 0.7, 0], dtype=np.float32),
        "dw": np.array([1, 0.7, 0], dtype=np.float32),
        "ds": np.array([1, 0, 1], dtype=np.float32),
        "as": np.array([-1, 0, 1], dtype=np.float32),
    },
    noop=np.array([0, 0, 0])
)

```

**Comment by kuds** [comment]
@pseudo-rnd-thoughts Awesome! That fixed it for me. I will create a pull request to update the documentation to reflect your code.
