### ISSUE TITLE
[Bug Report] check_step_determinism obscur working

### ISSUE THREAD

**Issue by qgallouedec** [Farama-Foundation/Gymnasium#1111]
### Describe the bug

It's the kind of issue that's hard to name or explain, or even reduce to simple code. But here's what I've observed since `check_step_determinism` was added: when I do the check myself, it passes. When it's the checker, it doesn't. For the moment the code depends on panda_gym, sorry for that, I'll reduce it in the past, but I wanted to postpone it as soon as possible.

### Code example

```python
import panda_gym
import gymnasium as gym
from gymnasium.utils.env_checker import check_env, data_equivalence

env = gym.make("PandaPickAndPlace-v3").unwrapped

seed = 123
env.action_space.seed(seed)
action = env.action_space.sample()
_, _ = env.reset(seed=seed)
obs_0, _, _, _, _ = env.step(action)
_, _ = env.reset(seed=seed)
obs_1, _, _, _, _ = env.step(action)

assert data_equivalence(obs_0, obs_1)  # Passes

check_env(env, skip_render_check=True)  # But! this fails in check_step_determinism
```

```
Traceback (most recent call last):
  File "/Users/quentingallouedec/panda-gym/94.py", line 16, in <module>
    check_env(env, skip_render_check=True)  # fails
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quentingallouedec/panda-gym/env/lib/python3.11/site-packages/gymnasium/utils/env_checker.py", line 402, in check_env
    check_step_determinism(env)
  File "/Users/quentingallouedec/panda-gym/env/lib/python3.11/site-packages/gymnasium/utils/env_checker.py", line 198, in check_step_determinism
    assert data_equivalence(
           ^^^^^^^^^^^^^^^^^
AssertionError: Deterministic step observations are not equivalent for the same seed and action
```

What's even weirder, is that it only happens in two environments. I'll keep digging and let you know.
### System info

Gymnasium 1.0.0a2
Panda-gym [10c4d8a](https://github.com/qgallouedec/panda-gym/commit/10c4d8adaab07d8a29b2f8dc0aa85f8edd8532ae)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
The only thing I can think of is perhaps your environment does not properly reset internal state after the second reset

Does this pass?:
```py
import panda_gym
import gymnasium as gym
from gymnasium.utils.env_checker import check_env, data_equivalence

env = gym.make("PandaPickAndPlace-v3").unwrapped

check_env(env, skip_render_check=True)  # does this fail??
```

**Comment by qgallouedec** [comment]
It fails. Doesn't make any sense 😅

**Comment by Kallinteris-Andreas** [comment]
I have no idea how, this is failing

`check_step_determinism` does the same thing:
https://github.com/Farama-Foundation/Gymnasium/blob/a09dcfdcf08c4d7417f98c25f5bfec9ab2ff110d/gymnasium/utils/env_checker.py#L188-L218

you could try adding a `breakpoint()` in line 210 and printing `obs_0` and `obs_1`, that might reveal something

**Comment by pseudo-rnd-thoughts** [comment]
I can reproduce the error but seems to two require a strange setup

You must reset, step, reset, step for the second step to fail equivalence

If I change the error to assert then I can discover the `obs["observation"]` is the problem. Plus if I subtract the two data points, we can see it is in the second half only, this is from the task
```python
AssertionError: data_1 - data_2=array([ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -4.6938658e-07,
        4.4703484e-07, -3.2596290e-07,  1.1971366e-05, -1.0663000e-05,
        3.4053983e-06,  2.5060897e-05, -7.6492070e-06, -2.2978888e-05,
        1.1928683e-03,  1.7360186e-03,  2.0111194e-04], dtype=float32)
```

Looking at all the environment, this is a problem for most of them except Reach and Slide
```python
import gymnasium as gym
from gymnasium.utils.env_checker import data_equivalence

import panda_gym
from panda_gym.envs import PandaPickAndPlaceEnv, PandaFlipEnv, PandaPushEnv, PandaReachEnv, PandaSlideEnv, PandaStackEnv

gym.register_envs(panda_gym)

for env_cls in [PandaPickAndPlaceEnv, PandaFlipEnv, PandaPushEnv, PandaReachEnv, PandaSlideEnv, PandaStackEnv]:
    env = env_cls()
    print(f'{env}')

    seed = 123
    env.action_space.seed(seed)
    action_0 = env.action_space.sample()
    action_1 = env.action_space.sample()

    obs_0, _ = env.reset(seed=seed)
    obs_1, _, _, _, _ = env.step(action_0)
    obs_2, _ = env.reset()
    obs_3, _, _, _, _ = env.step(action_1)

    obs_4, _ = env.reset(seed=seed)
    obs_5, _, _, _, _ = env.step(action_0)
    obs_6, _ = env.reset()
    obs_7, _, _, _, _ = env.step(action_1)

    data_equivalence(obs_0, obs_4)
    data_equivalence(obs_1, obs_5)
    print(f'{obs_1["observation"] - obs_5["observation"]=}')
    data_equivalence(obs_2, obs_6)
    data_equivalence(obs_3, obs_7)
```
Of which, all of these differences only exist in the task (not the robot)

**Comment by pseudo-rnd-thoughts** [comment]
I've found a sort of source for the noise in `observation`. 
The `_sample_object` function in `PushAndPlace` task, if you comment out line 83 that adds the noise to the object_position, `object_position += noise`, the error disappears to `PushAndPlace`. 
However, if you print the noise value produced, its the same in the two episodes. 
```python
noise=array([0.04380345, 0.00589226, 0.        ])
<PandaPickAndPlaceEnv instance>
noise=array([-0.09722823,  0.09362835,  0.        ])
noise=array([-0.07651062,  0.09727248,  0.        ])
noise=array([-0.09722823,  0.09362835,  0.        ])
noise=array([-0.07651062,  0.09727248,  0.        ])
obs_1["observation"] - obs_5["observation"]=array([ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -4.6938658e-07,
        4.4703484e-07, -3.2596290e-07,  1.1971366e-05, -1.0663000e-05,
        3.4053983e-06,  2.5060897e-05, -7.6492070e-06, -2.2978888e-05,
        1.1928683e-03,  1.7360186e-03,  2.0111194e-04], dtype=float32)
```
I can't figure out why adding this noise is causing the output to change
The problem is that if I change the code to 
```python
    def _sample_object(self) -> np.ndarray:
        """Randomize start position of object."""
        object_position = np.array([0.0, 0.0, self.object_size / 2])
        noise = self.np_random.uniform(self.obj_range_low, self.obj_range_high)
        object_position += np.array([-0.09722823,  0.09362835,  0.        ])
        return object_position
```
the problem persists even if we are still adding the noise

**Comment by pseudo-rnd-thoughts** [comment]
Looking at the next day, I can't replicate the problem I noted at the end

I tested the minimal example
```python
seed = 123
env.action_space.seed(seed)
action_0 = env.action_space.sample()
action_1 = env.action_space.sample()

obs_0, _ = env.reset(seed=seed)
obs_1, _, _, _, _ = env.step(action_0)
obs_2, _ = env.reset()
obs_3, _, _, _, _ = env.step(action_1)  # This line is necessary

obs_4, _ = env.reset(seed=seed)
obs_5, _, _, _, _ = env.step(action_0)
obs_6, _ = env.reset()
# obs_7, _, _, _, _ = env.step(action_1)  # This line isn't necessary for the issue

print(f'{obs_1["observation"] - obs_5["observation"]=}')
```

Another test I made was to add another reset case to compare the 3 observations
Interestingly, the three observations are different, meaning there is an unknown source of randomness that is deterministic (the observation error being constant across many runs). This is a very strange combination of deterministic unknown randomness
```python
seed = 123
env.action_space.seed(seed)
action_0 = env.action_space.sample()
action_1 = env.action_space.sample()

obs_0, _ = env.reset(seed=seed)
obs_1, _, _, _, _ = env.step(action_0)
obs_2, _ = env.reset()
obs_3, _, _, _, _ = env.step(action_1)  # necessary

obs_4, _ = env.reset(seed=seed)
obs_5, _, _, _, _ = env.step(action_0)
obs_6, _ = env.reset()
# obs_7, _, _, _, _ = env.step(action_1)  # unnecessary

obs_8, _ = env.reset(seed=seed)
obs_9, _, _, _, _ = env.step(action_0)
obs_10, _ = env.reset()
# obs_11, _, _, _, _ = env.step(action_1)  # unnecessary

print(f'{obs_1["observation"] - obs_5["observation"]=}')
print(f'{obs_5["observation"] - obs_9["observation"]=}')
print(f'{obs_1["observation"] - obs_9["observation"]=}')
```

Checking the seeding, separating the action space and reset seeding, only the reset seeding affects the observation, i.e., the actual action taken doesn't matter

The last check I've made is related to the `_sample_object` function and the noise. 
Rechecking, I couldn't replicate the constant noise still causing the issue

**Comment by CloseChoice** [comment]
In order to reproduce what `check_env` does, here is an example that fails:
```python
import panda_gym
import gymnasium as gym
from gymnasium.utils.env_checker import check_env, data_equivalence

env = gym.make("PandaPickAndPlace-v3").unwrapped

obs1, _ = env.reset()
obs2, _ = env.reset()

assert data_equivalence(obs1, obs2)  # Fails
```
The problem here is that the `observation` array is different:

```shell
(Pdb++) data_1['observation']
array([ 3.8439669e-02, -2.1944723e-12,  1.9740014e-01,  0.0000000e+00,
       -0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.4557141e-01,
       -3.3392582e-02,  2.0000000e-02,  0.0000000e+00, -0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00], dtype=float32)
(Pdb++) data_2['observation']
array([ 3.8439669e-02, -2.1944723e-12,  1.9740014e-01,  0.0000000e+00,
       -0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  5.1143125e-02,
        4.2222742e-02,  2.0000000e-02,  0.0000000e+00, -0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00], dtype=float32)
```
See index 7 and 8. This is not a problem with Gymnasium but rather with panda_env.

**Comment by amacati** [comment]
Not sure if this is still relevant, but this could be another instance of a sim solver warmstart that messes with reproducibility. If the pybullet solvers are using internal variables and are not properly reset, the physics step will be slightly different. This may only manifest itself in some of the environments or when checking with sufficiently tight tolerances.

We had a similar situation with gymnasium-robotics and mujoco. See https://github.com/Farama-Foundation/Gymnasium-Robotics/issues/207

**Comment by omnilink-tech** [comment]
This reproduces on current versions, and it turns out to be **two independent
bugs, one masking the other**. The first is a one-line fix in panda_gym and
explains why `check_env` fails on *every* environment. The second is the one
this issue is actually about, and I can now say fairly precisely what it is not.

Versions: gymnasium 1.3.0, panda_gym 3.0.7, pybullet build 202010061
(2025-10-10), numpy 2.5.2, Python 3.12.9, Windows.

---

## 1. The failure everyone has been looking at is not `check_step_determinism`

Running the original snippet, the assertion that actually fires is:

```
Using `env.reset(seed=123)` then `env.reset()` is non-deterministic
as the observations are not equivalent.
```

That is the **reset** check at
[`env_checker.py:118`](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/utils/env_checker.py#L118),
not `check_step_determinism`. It runs earlier, so it is what `check_env` reports
— which I think explains a lot of the confusion in this thread, including why
@qgallouedec's manual reset/step/reset/step check passed while `check_env`
failed. The manual check was testing a different property from the one that was
failing.

The checker is right to complain. It does:

```
obs_1 = reset(seed=123)   # RNG <- 123
obs_2 = reset()           # RNG advances from that state
obs_3 = reset(seed=123)   # RNG <- 123 again
obs_4 = reset()           # RNG should advance identically
assert obs_2 == obs_4
```

`obs_2 == obs_4` must hold for any env that draws its randomness from
`self.np_random`. panda_gym does not:

**[`panda_gym/envs/core.py:280`](https://github.com/qgallouedec/panda-gym/blob/master/panda_gym/envs/core.py)**

```python
super().reset(seed=seed, options=options)
self.task.np_random, seed = seeding.np_random(seed)   # <-- every reset
```

This runs unconditionally. On an unseeded reset `seed is None`, and
`seeding.np_random(None)` returns a **brand-new generator seeded from OS
entropy** — unrelated to `env.np_random`, which `super().reset()` has just
managed correctly. So `reset(seed=123)` is reproducible, but every subsequent
unseeded reset draws from fresh entropy.

Measured on `PandaPickAndPlace-v3`:

```
obs_1 == obs_3  (same seed)            : True
obs_2 == obs_4  (unseeded after seed)  : False
   differing indices: [7 8]   <- object x, y
env.task.np_random is env.np_random    : False
```

### One-line fix

```python
 super().reset(seed=seed, options=options)
-self.task.np_random, seed = seeding.np_random(seed)
+self.task.np_random = self.np_random
```

The task then shares the env's properly-seeded generator, which is the usual
Gymnasium pattern.

**A/B over all 20 constructible Panda envs** (the 4 `Flip` ones fail to build
here on an unrelated `loadTexture` error):

| | result |
|---|---|
| panda_gym as shipped | **20 fail**, all at the *reset* check |
| with the one-line fix | **11 pass**, 8 fail at the *step* check |

Stochasticity is preserved — two bare `reset()` calls still produce different
object positions, as they should. And note the original report says "it only
happens in two environments"; it is actually all of them.

---

## 2. The remaining 8 failures are the real subject of this issue

With the RNG bug fixed, `check_step_determinism` fails on exactly the
environments that contain a free-floating object (`Push*Dense`, all four
`PickAndPlace`, `Stack*Dense`). This is the original bug, previously hidden
behind the reset failure.

It reproduces exactly as @pseudo-rnd-thoughts described — an intervening
episode is required:

```
reset(42), step(a) twice back to back      : max|d| = 0.000e+00
reset(42), step(a) with an episode between : max|d| = 1.002e-03
```

Only the object diverges; the robot is bit-identical:

```
[ 0..6] ee position, velocity, fingers   0.000000e+00
[ 7] obj_x   2.548099e-06        [13] obj_vx  5.537329e-05
[ 8] obj_y   1.326203e-06        [14] obj_vy  3.276886e-05
[ 9] obj_z   1.639128e-07        [15] obj_vz  1.727123e-06
[10] obj_rx  6.119823e-06        [16] obj_wx  7.811328e-05
[11] obj_ry  4.412252e-05        [17] obj_wy  3.298254e-04
[12] obj_rz  3.781682e-05        [18] obj_wz  1.001758e-03
```

### The inputs are provably identical

I dumped the **complete observable simulator state** after `reset(seed=42)` in
both trials — every base position, orientation, linear and angular velocity, and
every joint's position, velocity and applied torque, across all five bodies
(`panda`, `plane`, `table`, `object`, `target`): **101 components**.

```
FULL sim state after reset: n=101   max|d| = 0.000e+00   (0 components differ)
```

Identical state, identical action, identical seed — and one `step()` later the
object has moved differently. So whatever carries the difference is **not
exposed through any PyBullet getter**.

### What it is not

Each of these was run as its own arm; all reproduce the same 1.002e-03:

| hypothesis | result |
|---|---|
| solver warm-start (`warmStartingFactor=0.0`) | **refuted** — 1.002e-03, unchanged |
| `deterministicOverlappingPairs=1` | **refuted** — 1.002e-03, unchanged |
| body sleep (`ACTIVATION_STATE_DISABLE_SLEEPING`, and explicit `WAKE_UP`) | **refuted** — 1.002e-03, unchanged |
| object velocity surviving reset | **refuted** — I forced `v=[3,-2,1]`, `w=[5,4,-3]`; `resetBasePositionAndOrientation` zeroes both |
| RNG / task noise | **refuted** — sampled object pose is bit-identical at reset |

@amacati's warm-start suggestion was the natural one given the
Gymnasium-Robotics precedent, but disabling warm-start changes the divergence by
nothing at all, so unlike the MuJoCo case it does not appear to be the mechanism
here.

### What it is

The one thing that does change it is whether the physics client is reused:

```
fresh pybullet client per trial : max|d| = 0.000e+00
one client reused across trials : max|d| = 1.002e-03
```

So the divergence is carried entirely by persistent internal state in the
PyBullet client — solver caches, island/manifold bookkeeping, or allocation
ordering — that survives `resetBasePositionAndOrientation` and `resetJointState`
and is not reachable through the public API. That is consistent with every
observation in this thread: it needs a prior episode, it only touches the free
body, it is ~1e-3 on angular velocity, and it vanishes if you look at it from a
clean process (which is why it was so hard to pin down).

---

## Suggested split

These are two different problems and I think they want two different homes:

1. **The RNG bug is panda_gym's** and the fix above is complete — happy to open
   it there if that is useful, or leave it to @qgallouedec since it is a
   one-liner in his own repo.
2. **The step divergence is arguably neither Gymnasium's nor panda_gym's.** Both
   are behaving correctly: the env restores every piece of state it can address,
   and the checker correctly reports that the result is not reproducible. If it
   is upstream PyBullet state, then `PandaPickAndPlace-v3` and friends may
   genuinely warrant `nondeterministic=True` in their spec until the underlying
   engine can guarantee it, rather than being treated as an env bug.

Scripts for every measurement above are short and self-contained (no panda_gym
internals patched except the one line) — glad to attach any of them if you want
to re-run something independently.

**Comment by omnilink-tech** [comment]
Correction to my previous comment, on section 1.

That RNG fix is **not new — it is already in panda_gym master**, and has been
since `10c4d8ada` ("Better seed", #97, 2024-07-04). I presented it as a proposal;
it is not. Apologies for the noise.

What is true, and I think still worth knowing:

- **v3.0.7 was released 2024-06-10, and the fix landed 24 days later. There has
  been no release since.** So `pip install panda-gym` still gives you the version
  with `self.task.np_random, seed = seeding.np_random(seed)`, and on that version
  **all 20 constructible Panda envs fail `check_env`** at the reset check — which
  is what I was measuring. A release would fix that for everyone installing from
  PyPI.
- The original report here cites panda-gym `10c4d8a` — i.e. @qgallouedec was
  already on the fixed commit. So the failure he reported was never the RNG bug;
  it was the step divergence, which is exactly what this issue is titled about.
  My section 1 was describing the released version, not the one in the report.

**Section 2 is unaffected**, and it is the part I would actually stand behind.
Re-running it against master's seeding behaviour (which is what my "fixed" arm
was), the result is unchanged:

- `reset(42), step(a)` twice back to back: `max|d| = 0.000e+00`
- the same with one intervening episode: `max|d| = 1.002e-03`
- the complete observable simulator state after reset — 101 components across
  all five bodies, every pose, velocity, joint position, joint velocity and
  applied torque — is **bit-identical** in both trials
- warm-start, `deterministicOverlappingPairs`, body sleep, and object velocity
  surviving reset are each **refuted** individually, all still 1.002e-03
- a **fresh physics client per trial gives `0.000e+00`**; reusing one client
  gives 1.002e-03

So the open question is unchanged and, I think, sharper: with provably identical
inputs, one `step()` produces different object dynamics depending only on whether
that PyBullet client has previously run an episode. That points at persistent
engine state rather than at anything panda_gym or the checker is doing wrong.

Which also means @qgallouedec's 2024-07-23 note on
[panda-gym#94](https://github.com/qgallouedec/panda-gym/issues/94) —
"I've only managed to solve the issue with some environments, I can't solve it
for the others" — is very likely not a gap in that fix. The environments left
unchecked there are precisely the ones with a free-floating object, and those are
the eight that still fail here for a reason outside the library.
