### ISSUE TITLE
[Bug Report] Error in Env Rendering Due to Current Dependency Installation

### ISSUE THREAD

**Issue by DocyNoah** [Farama-Foundation/Gymnasium#1134]
### Describe the bug

After installing the package using `pip install 'gymnasium[classic-control]'`, when creating an environment with `env = gym.make(env_name, render_mode="human")` and calling `env.step()`, a `TypeError: size must be two numbers` occurs.

Specifically, this issue does not occur with the CartPole and MountainCar environments, but it does occur with the Pendulum environment.

This issue is caused by the upgrade to numpy 2.0 in June. Downgrading to the latest 1.x version, 1.26.4, fixes the bug. Therefore, it is necessary to either change the dependency from “numpy >=1.21.0” to “numpy >=1.21.0,<2.0” or adjust the pygame render code where the error occurs.

### Code example

terminal
```bash
pip install 'gymnasium[classic-control]'
python test.py
```

test.py
```python
import gymnasium

env = gymnasium.make("Pendulum-v1", render_mode="human")
env.reset()
action = env.action_space.sample()
env.step(action)
env.close()
```

Output
```bash
Traceback (most recent call last):
  File ".../test.py", line 6, in <module>
    env.step(action)
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/wrappers/time_limit.py", line 57, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
                                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/wrappers/env_checker.py", line 49, in step
    return env_step_passive_checker(self.env, action)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/utils/passive_env_checker.py", line 208, in env_step_passive_checker
    result = env.step(action)
             ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/envs/classic_control/pendulum.py", line 143, in step
    self.render()
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/envs/classic_control/pendulum.py", line 237, in render
    scale_img = pygame.transform.smoothscale(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: size must be two numbers

Process finished with exit code 1
```

***

terminal
```bash
pip install 'gymnasium[classic-control]'==1.0.0a2
python test.py
```

test.py
```python
import gymnasium

env = gymnasium.make("Pendulum-v1", render_mode="human")
env.reset()
action = env.action_space.sample()
env.step(action)
env.close()
```

Output
```bash
Traceback (most recent call last):
  File ".../test.py", line 6, in <module>
    env.step(action)
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/wrappers/common.py", line 121, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
                                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/wrappers/common.py", line 408, in step
    return super().step(action)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/core.py", line 317, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/wrappers/common.py", line 298, in step
    return env_step_passive_checker(self.env, action)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/utils/passive_env_checker.py", line 215, in env_step_passive_checker
    result = env.step(action)
             ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/envs/classic_control/pendulum.py", line 147, in step
    self.render()
  File "/opt/anaconda3/envs/test/lib/python3.11/site-packages/gymnasium/envs/classic_control/pendulum.py", line 242, in render
    scale_img = pygame.transform.smoothscale(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: size must be two numbers

Process finished with exit code 1
```

### Additional context

This bug is caused by a conflict between `pygame.transform.smoothscale()` in `gymnasium/envs/classic_control/pendulum.py` and the numpy 2.0 API.

terminal
```bash
pip install 'gymnasium[classic-control]'
pip install numpy==1.26.4
python test.py
```

test.py
```python
import gymnasium

env = gymnasium.make("Pendulum-v1", render_mode="human")
env.reset()
action = env.action_space.sample()
env.step(action)
env.close()
```

Output
```bash
Process finished with exit code 0
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the issue, we have fixed this in main already
