### ISSUE TITLE
[Question] Using `make` with ALE/Atari envs throws "Namespace ALE not found."

### ISSUE THREAD

**Issue by sven1977** [Farama-Foundation/Gymnasium#116]
### Question

Hey everyone, awesome work on the new repos and gymnasium/gym (>=0.26) APIs! We are very excited to be enhancing our RLlib to support these very soon. The current PR is already in good shape (literally had to touch every single line of RLlib :D ). However, one remaining problem for testing this is that Atari envs don't seem to run on gymnasium on my Mac (and in our Linux CI). Here is my repro:

```
$ # clean conda env
$ pip install gymnasium[atari] gymnasium[accept-rom-license] ale_py autorom
$ autorom
>> Y

$ python
>>> import gymnasium as gym
>>> gym.make("ALE/Pong-v5")
```

Throws error:
```
Traceback (most recent call last):
  File "/Users/sven/opt/anaconda3/envs/ray/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-a6c3b954198a>", line 1, in <module>
    make("ALE/Pong-v5")
  File "/Users/sven/opt/anaconda3/envs/ray/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 569, in make
    _check_version_exists(ns, name, version)
  File "/Users/sven/opt/anaconda3/envs/ray/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 219, in _check_version_exists
    _check_name_exists(ns, name)
  File "/Users/sven/opt/anaconda3/envs/ray/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 187, in _check_name_exists
    _check_namespace_exists(ns)
  File "/Users/sven/opt/anaconda3/envs/ray/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 182, in _check_namespace_exists
    raise error.NamespaceNotFound(f"Namespace {ns} not found. {suggestion_msg}")
gymnasium.error.NamespaceNotFound: Namespace ALE not found. Have you installed the proper package for ALE?
```

Anything else I'm missing here?

The same procedure works 100% fine when using gym instead of gymnasium.

**Comment by pseudo-rnd-thoughts** [comment]
Sadly, Ale-py has not updated to gymnasium. We are working on it.
For now, you need to use the gym compatibility env as shown in this example https://gymnasium.farama.org/content/gym_compatibility/

**Comment by pseudo-rnd-thoughts** [comment]
No worries, the compatibility wrapper should make all of the changes necessary to be compatible with gymnasium and works for all environments compatible with gym v26.

**Comment by shengdongxue123** [comment]
the variable of render_mode is not support in this gym.make("GymV26Environment-v0", env_id="ALE/Pong-v5")?
