### ISSUE TITLE
[Bug Report] Install gymnasium with atari games using conda

### ISSUE THREAD

**Issue by TheophileChampion** [Farama-Foundation/Gymnasium#1258]
### Describe the bug

When trying to install gymnasium with Atari games using conda, I get various error messages, for example:
- `No module named 'ale_py'`
- `No such file or directory: '[...]/ale_py/roms/pong.bin'`

### Code example

```shell
My setup.py:

from setuptools import find_packages
from setuptools import setup

setup(
    name="benchmarks",
    version="0.0.0",
    ...
    packages=find_packages(),
    scripts=["scripts/run_training"],
    include_package_data=True,
    install_requires=[
        # "gymnasium==1.0.0",
        # or "gymnasium-atari==1.0.0",
        # or "gymnasium-all==1.0.0", 
        "pytorch==2.5.1",
        "pytorchrl==0.6.0",
    ],
    python_requires="~=3.11",
    ...
)
```

My code:

```
import gymnasium as gym
import ale_py

if __name__ == '__main__':
    gym.register_envs(ale_py)
    env = gym.make("ALE/Pong-v5")
```

When I import "gymnasium==1.0.0", I get the error:

```
ModuleNotFoundError: No module named 'ale_py'
```

When I import "gymnasium-atari==1.0.0", I get the error:

```
FileNotFoundError: [Errno 2] No such file or directory: '[...]/lib/python3.11/site-packages/ale_py/roms/pong.bin'
```

When I import "gymnasium-all==1.0.0", I get the error:

```
FileNotFoundError: [Errno 2] No such file or directory: '[...]/lib/python3.11/site-packages/ale_py/roms/pong.bin'
```

I have also tried to import "ale_py==0.10.1" but it seems to be a dependency of both previously mentioned packages, and did not change anything.
```


### System info

Ubuntu 24.04.1 LTS
Gymnasium 1.0.0
Python 3.11
Conda 24.5.0

### Additional context

_No response_

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Nikhil-24-04** [comment]
import gymnasium as gym

if __name__ == '__main__':
    env = gym.make("ALE/Pong-v5", render_mode="human")
    observation, info = env.reset()

    for _ in range(1000):
        env.render()
        action = env.action_space.sample()
        observation, reward, terminated, truncated, info = env.step(action)
        if terminated or truncated:
            observation, info = env.reset()

    env.close()

**Comment by TheophileChampion** [comment]
Thanks for you answer, I have tried many things including this variation. Unfortunately, I still get the same errors.

Just to make it clear my problem is about using `conda`, more specifically `setup.py` to create a package.

For example, I am able to install gymnasium using `pip` and `requirements.txt` as follows:
```
gymnasium[atari, accept-rom-licesnse]==1.0.0
torch==2.5.1
torchrl==0.6.0
tensorboard==2.18.0
```

Then, the following code runs:
```
import gymnasium as gym
import ale_py


if __name__ == '__main__':
    env = gym.make("ALE/Pong-v5", render_mode="human")
    observation, info = env.reset()

    for _ in range(1000):
        env.render()
        action = env.action_space.sample()
        observation, reward, terminated, truncated, info = env.step(action)
        if terminated or truncated:
            observation, info = env.reset()

    env.close()
```

Note, `import ale_py` is actually useful as otherwise I get the following error:
```
Traceback (most recent call last):
  File "/home/theophile/Desktop/portfolio/ReinforcementLearningBenckmarks/scripts/run_training.py", line 25, in <module>
    env = gym.make("ALE/Pong-v5", render_mode="human")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theophile/Desktop/portfolio/ReinforcementLearningBenckmarks/rl-bench-venv/lib/python3.12/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
               ^^^^^^^^^^^^^^
  File "/home/theophile/Desktop/portfolio/ReinforcementLearningBenckmarks/rl-bench-venv/lib/python3.12/site-packages/gymnasium/envs/registration.py", line 531, in _find_spec
    _check_version_exists(ns, name, version)
  File "/home/theophile/Desktop/portfolio/ReinforcementLearningBenckmarks/rl-bench-venv/lib/python3.12/site-packages/gymnasium/envs/registration.py", line 397, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/theophile/Desktop/portfolio/ReinforcementLearningBenckmarks/rl-bench-venv/lib/python3.12/site-packages/gymnasium/envs/registration.py", line 360, in _check_name_exists
    _check_namespace_exists(ns)
  File "/home/theophile/Desktop/portfolio/ReinforcementLearningBenckmarks/rl-bench-venv/lib/python3.12/site-packages/gymnasium/envs/registration.py", line 354, in _check_namespace_exists
    raise error.NamespaceNotFound(f"Namespace {ns} not found. {suggestion_msg}")
gymnasium.error.NamespaceNotFound: Namespace ALE not found. Have you installed the proper package for ALE?
```

**Comment by pseudo-rnd-thoughts** [comment]
Apologies, I thought this was fixed, I would use `pip install ale-py` if you using `gymnasium>=1.0` as the conda package for `ale-py` is broken currently. 
I'm working on a fix

**Comment by TheophileChampion** [comment]
Sounds good, for now I am using the `requirements.txt` with pip and everything works fine.

**Comment by tlloubna** [comment]
Hey, I have the same error when trying to install an Atari game for my DDQN algorithm, but I don't know how to fix it. Please let me know if you find out how to install and configure it on my computer.

**Comment by TheophileChampion** [comment]
Without more information about your setup it will be difficult to help. Are you on Linux, MacOS, or Windows? Also, are you using a requirements.txt (with pip), conda, poetry (or something else)?

On Linux, you should be able to create a file named `requirements.txt`, then you can use the following command:
```
pip install -r requirements.txt
```

The content of a requirements file that worked on my machine can be found above, also see the answer of @pseudo-rnd-thoughts if you want to use `gymnasium>=1.0`.

**Comment by pseudo-rnd-thoughts** [comment]
If users are installing ale-py from conda then the roms are not packaged with the install for which the pypi version of ale-py does. 
I would recommend uninstall ale-py from conda and install from pypi with `pip install ale-py`.

**Comment by traversaro** [comment]
xref: https://github.com/conda-forge/ale-py-feedstock/pull/20 . The main blocking issue on the conda side is that the legal situation w.r.t. to redistribution of the rom is not clear.

**Comment by TheophileChampion** [comment]
> As without proper licensing we can't distribute ROMs on conda-forge, we mitigated the issue in [conda-forge/ale-py-feedstock#26](https://github.com/conda-forge/ale-py-feedstock/pull/26) by documenting how external ROMs can be loaded. [@TheophileChampion](https://github.com/TheophileChampion) is that sufficient to solve the issue for you?

Yes, I using pip worked for me :)

**Comment by h-vetinari** [comment]
It's not really resolved, we're just using people to use work-arounds (reinstalling with pip instead of conda). It'd be good to clear up the license situation for ROMs, then conda-forge could distribute it as well (I'd say the same goes for pip, but clearly that doesn't seem to concern people overmuch).
