### ISSUE TITLE
[Bug Report] Cannot make an environment in env.registry

### ISSUE THREAD

**Issue by mzat-msft** [Farama-Foundation/Gymnasium#152]
### Describe the bug

Hello,

When trying to make an environment in ``gym.registry`` I get a ``NameNotFound`` error, even though the environment should be found as I am picking the name from ``gym.registry``.

```python
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gymnasium as gym
>>> gym.make("YarsRevengeNoFrameskip-v4")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marc/.venvs/bonsai-gym/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 569, in make
    _check_version_exists(ns, name, version)
  File "/home/marc/.venvs/bonsai-gym/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 219, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/marc/.venvs/bonsai-gym/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 197, in _check_name_exists
    raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment YarsRevengeNoFrameskip doesn't exist.
```

As you can see:

```python
>>> from gym import envs
>>> envs.registry['YarsRevengeNoFrameskip-v4']
EnvSpec(id='YarsRevengeNoFrameskip-v4', entry_point='ale_py.env.gym:AtariEnv', reward_threshold=None, nondeterministic=False, max_episode_steps=None, order_enforce=True, autoreset=False, disable_env_checker=False, apply_api_compatibility=False, kwargs={'game': 'yars_revenge', 'obs_type': 'rgb', 'repeat_action_probability': 0.0, 'full_action_space': False, 'max_num_frames_per_episode': 108000, 'frameskip': 1}, namespace=None, name='YarsRevengeNoFrameskip', version=4)
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Ale-py has not updated to gymnasium yet sadly. 
I will update the release notes. 
This will be fixed in the next release, in the meantime you can use 'pip install shimmy[atari]' or using the gym compatibility Env (see the website info)

**Comment by mzat-msft** [comment]
Oh sorry, I got confused and did not consider that I was talking about a `gym` environment and not a `gymnasium` one. Sorry for that
