### ISSUE TITLE
[Bug Report] import gymnasium causes TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by martinkunev** [Farama-Foundation/Gymnasium#374]
### Describe the bug

Importing `gymnasium` causes a python exception to be raised.

```
$ python3 -c 'import gymnasium as gym'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/martin/.local/lib/python3.9/site-packages/gymnasium/__init__.py", line 12, in <module>
    from gymnasium.envs.registration import make, spec, register, registry, pprint_registry
  File "/home/martin/.local/lib/python3.9/site-packages/gymnasium/envs/__init__.py", line 364, in <module>
    load_env_plugins()
  File "/home/martin/.local/lib/python3.9/site-packages/gymnasium/envs/registration.py", line 273, in load_env_plugins
    for plugin in metadata.entry_points(group=entry_point):
  File "/home/martin/.local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 856, in entry_points
    return EntryPoints(eps).select(**params)
  File "/home/martin/.local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 853, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/home/martin/.local/lib/python3.9/site-packages/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/home/martin/.local/lib/python3.9/site-packages/importlib_metadata/_py39compat.py", line 18, in normalized_name
    return dist._normalized_name
  File "/home/martin/.local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 778, in _normalized_name
    or super()._normalized_name
  File "/home/martin/.local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 445, in _normalized_name
    return Prepared.normalize(self.name)
  File "/home/martin/.local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 700, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

### System info

```
$ pip3 install 'gymnasium[atari]'
Collecting gymnasium[atari]
  Downloading gymnasium-0.27.1-py3-none-any.whl (883 kB)
     |████████████████████████████████| 883 kB 775 kB/s 
Collecting typing-extensions>=4.3.0
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting cloudpickle>=1.2.0
  Downloading cloudpickle-2.2.1-py3-none-any.whl (25 kB)
Collecting jax-jumpy>=0.2.0
  Downloading jax_jumpy-0.2.0-py3-none-any.whl (11 kB)
Collecting numpy>=1.21.0
  Downloading numpy-1.24.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     |████████████████████████████████| 17.3 MB 1.4 MB/s 
Collecting gymnasium-notices>=0.0.1
  Downloading gymnasium_notices-0.0.1-py3-none-any.whl (2.8 kB)
Collecting importlib-metadata>=4.8.0
  Downloading importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
Collecting shimmy[atari]<1.0,>=0.1.0
  Downloading Shimmy-0.2.1-py3-none-any.whl (25 kB)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata>=4.8.0->gymnasium[atari]) (1.0.0)
Collecting ale-py~=0.8.1
  Downloading ale_py-0.8.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 1.4 MB/s 
Collecting importlib-resources
  Downloading importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting zipp>=0.5
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Installing collected packages: zipp, numpy, typing-extensions, jax-jumpy, importlib-metadata, gymnasium-notices, cloudpickle, importlib-resources, gymnasium, shimmy, ale-py
  WARNING: The scripts f2py, f2py3 and f2py3.9 are installed in '/home/martin/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script ale-import-roms is installed in '/home/martin/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed ale-py-0.8.1 cloudpickle-2.2.1 gymnasium-0.27.1 gymnasium-notices-0.0.1 importlib-metadata-6.0.0 importlib-resources-5.12.0 jax-jumpy-0.2.0 numpy-1.24.2 shimmy-0.2.1 typing-extensions-4.5.0 zipp-3.15.0
```

```
$ python3 --version
Python 3.9.2
```

I'm using Debian 11.

### Additional context

Debugging the import code, I can see that in the following method:

```
@property
def _normalized_name(self):
    """Return a normalized version of the name."""
    print(self.name)
    return Prepared.normalize(self.name)
```

The value of self.name is `None`.

I verified that my python installation works correctly and imports of other modules don't generate this error.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by martinkunev** [comment]
Thanks for the fast reaction!
After further investigation, I was able to fix this.

I was testing on my local system. I was seeing the exception when running with a regular user but not with root. After some debugging, I figured out there is an egg file (`kubernetes-25.3.0-py3.9.egg`) which seems to interfere with gymnasium. Removing the file fixes the issue.

Given that it worked with root, I'm suspecting the problem had something to do with permissions. I have no idea how exactly kubernetes causes problems specifically with gymnasium and not with other modules like numpy or matplotlib. I'm not sure if importing gymnasium triggers some deep chain of dependencies. In any case the problem seems to be somewhere else so this bug should probably be closed.

I'm providing the output of freeze in case somebody finds this helpful.
```
$ pip freeze
attrs==20.3.0
awscli==1.19.1
beautifulsoup4==4.9.3
botocore==1.20.0
cached-property==1.5.2
cachetools==5.1.0
cajarename==20.1.26
camset==0.0.19
certifi==2020.6.20
chardet==3.0.4
charset-normalizer==2.0.12
click==8.1.3
click-default-group==1.2.2
cloudpickle==2.2.1
cloup==0.13.1
colorama==0.4.4
colour==0.1.5
commonmark==0.9.1
configobj==5.0.6
coverage==7.0.5
crcmod==1.7
cryptography==3.3.2
cycler==0.10.0
dbus-python==1.2.16
decorator==5.1.1
distro==1.5.0
distro-info==1.0
docker==4.1.0
docker-compose==1.25.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.16
evdev==1.4.0
glcontext==2.3.6
google-api-core==2.7.3
google-api-python-client==2.47.0
google-auth==2.6.6
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.5.1
googleapis-common-protos==1.56.1
gpg===1.14.0-unknown
gymnasium==0.27.1
gymnasium-notices==0.0.1
gyp==0.1
html5lib==1.1
httplib2==0.18.1
idna==2.7
importlib-metadata==6.0.0
iniconfig==0.0.0
isosurfaces==0.1.0
jax-jumpy==0.2.0
jmespath==0.10.0
joblib==1.1.0
jsonschema==3.2.0
kiwisolver==1.3.1
kubernetes==25.3.0
kubernetes-client==0.1.7
lxml==4.6.3
manim==0.15.2
manimlib==0.2.0
ManimPango==0.4.1
mapbox-earcut==0.12.11
mate-menu==20.4.1
mate-tweak==21.4.2
matplotlib==3.3.4
moderngl==5.6.4
moderngl-window==2.4.1
more-itertools==4.2.0
mpmath==1.2.1
multidict==6.0.2
multipledispatch==0.6.0
mypy==0.991
mypy-extensions==0.4.3
networkx==2.8.2
nonconformist==2.1.0
numpy==1.24.2
oauthlib==3.2.0
olefile==0.46
opencv-python==4.5.5.64
packaging==20.9
pandas==1.4.1
Pillow==9.1.1
pluggy==0.13.0
progressbar==2.5
protobuf==3.20.1
psutil==5.8.0
pulsar-client==2.9.1
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyC8==0.16.9
pycairo==1.21.0
pycurl==7.43.0.6
pydantic==1.9.0
pydub==0.25.1
pygame==1.9.6
pyglet==1.5.26
Pygments==2.12.0
PyGObject==3.38.0
PyICU==2.5
PyOpenGL==3.1.5
pyparsing==2.4.7
pyrr==0.10.3
pyrsistent==0.15.5
pystache==0.5.4
pytest==6.0.2
pytest-cov==4.0.0
python-apt==2.2.1
python-dateutil==2.8.1
python-debian==0.1.39
python-magic==0.4.20
python-xlib==0.29
pytz==2021.3
pyxdg==0.27
PyYAML==6.0
requests==2.27.1
requests-oauthlib==1.3.1
rich==12.4.4
roman==2.0.0
rsa==4.0
s3transfer==0.3.4
scikit-learn==1.1.1
scipy==1.8.1
screeninfo==0.8
semver==2.10.2
setproctitle==1.2.1
six==1.16.0
skia-pathops==0.7.2
sklearn==0.0
soupsieve==2.2.1
srt==3.5.2
sympy==1.10.1
table-logger==0.3.6
texttable==1.6.3
threadpoolctl==3.1.0
toml==0.10.1
tomli==2.0.1
tqdm==4.64.0
typing_extensions==4.5.0
unattended-upgrades==0.1
uritemplate==4.1.1
urllib3==1.24.3
watchdog==2.1.8
webencodings==0.5.1
websocket-client==0.57.0
xdg==5
XlsxWriter==3.0.2
xlwt==1.3.0
zipp==1.0.0
```

**Comment by pseudo-rnd-thoughts** [comment]
I just saw that this is the same error as https://github.com/Farama-Foundation/Gymnasium/issues/428
