### ISSUE TITLE
[Bug Report] mujoco.FatalError: gladLoadGL error while rendering Mujoco environments

### ISSUE THREAD

**Issue by ygrayson** [Farama-Foundation/Gymnasium#411]
### Describe the bug

Hello,

I've run into this error while trying to render any Mujoco environments on a headerless machine with `rgb_array` render mode. My installation for the environment was `pip install gymnasium` and `pip install mujoco`. Does anyone know what might be the cause for this? Thanks.

```
>>> env = gym.make("Ant-v4", render_mode="rgb_array")
>>> env.render()
/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/glfw/__init__.py:912: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/glfw/__init__.py:912: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
  File "/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py", line 70, in render
    return self.env.render(*args, **kwargs)
  File "/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/gymnasium/wrappers/env_checker.py", line 63, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
  File "/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py", line 391, in env_render_passive_checker
    result = env.render()
  File "/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 379, in render
    return self.mujoco_renderer.render(
  File "/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 646, in render
    viewer = self._get_viewer(render_mode=render_mode)
  File "/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 686, in _get_viewer
    self.viewer = OffScreenViewer(self.model, self.data)
  File "/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 144, in __init__
    super().__init__(model, data, width, height)
  File "/nfs/nhome/live/gyin/miniconda3/envs/rl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 61, in __init__
    self.con = mujoco.MjrContext(self.model, mujoco.mjtFontScale.mjFONTSCALE_150)
mujoco.FatalError: gladLoadGL error
```

### Code example

```shell
import gymnasium as gym
env_name = "Ant-v4"
env = gym.make(env_name, render_mode="depth_array")

state, _ = env.reset()
img = env.render()
```

### System info

Gymnasium is install within `conda` environment using `pip`:

```
(rl) gyin@hpc-gw1:~/repos/exploratory_projects$ conda list gymnasium
# packages in environment at /nfs/nhome/live/gyin/miniconda3/envs/rl:
#
# Name                    Version                   Build  Channel
gymnasium                 0.28.1                   pypi_0    pypi
gymnasium-notices         0.0.1                    pypi_0    pypi
(rl) gyin@hpc-gw1:~/repos/exploratory_projects$ conda list mujoco
# packages in environment at /nfs/nhome/live/gyin/miniconda3/envs/rl:
#
# Name                    Version                   Build  Channel
mujoco                    2.3.3                    pypi_0    pypi
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
If you use a new virtual environment (not conda) and run `pip install "gymnasium[mujoco]"` does this still not work?

**Comment by ygrayson** [comment]
Thanks for your reply @pseudo-rnd-thoughts. I installed virtual environment from system python afresh and ran the code. Now I got a different error below:

Installation:
```
gyin@hpc-gw1:~/repos/exploratory_projects/locomotion_agent$ python3 -m venv env
gyin@hpc-gw1:~/repos/exploratory_projects/locomotion_agent$ source env/bin/activate
(env) gyin@hpc-gw1:~/repos/exploratory_projects/locomotion_agent$ pip install gymnasium[mujoco]
```

Running the code:
```
(env) gyin@hpc-gw1:~/repos/exploratory_projects/locomotion_agent$ python
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gymnasium as gym
>>> env = gym.make("Ant-v4", render_mode="rgb_array")
>>> env.reset()
(array([ 8.38464470e-01,  9.95581305e-01,  1.62438436e-02, -9.08616692e-02,
        1.72673282e-02, -7.84957791e-02, -7.25393779e-04,  6.97520572e-02,
       -5.63103967e-02,  7.68487219e-02, -8.87238945e-02, -1.43015349e-02,
        7.96906579e-02, -2.27694935e-02, -4.05470203e-02, -9.00845252e-02,
        9.76482651e-02, -1.42370677e-01,  1.40744876e-01,  1.07789492e-01,
       -1.54321927e-01,  2.09253104e-02, -6.54008002e-02,  1.65583194e-01,
       -9.43582602e-02,  8.12992646e-02, -1.55947772e-01]), {})
>>> env.render()
/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
  File "/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/gymnasium/wrappers/order_enforcing.py", line 70, in render
    return self.env.render(*args, **kwargs)
  File "/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/gymnasium/wrappers/env_checker.py", line 63, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
  File "/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/gymnasium/utils/passive_env_checker.py", line 391, in env_render_passive_checker
    result = env.render()
  File "/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 379, in render
    return self.mujoco_renderer.render(
  File "/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 646, in render
    viewer = self._get_viewer(render_mode=render_mode)
  File "/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 686, in _get_viewer
    self.viewer = OffScreenViewer(self.model, self.data)
  File "/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 144, in __init__
    super().__init__(model, data, width, height)
  File "/nfs/nhome/live/gyin/repos/exploratory_projects/locomotion_agent/env/lib/python3.8/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 61, in __init__
    self.con = mujoco.MjrContext(self.model, mujoco.mjtFontScale.mjFONTSCALE_150)
mujoco.FatalError: an OpenGL platform library has not been loaded into this process, this most likely means that a valid OpenGL context has not been created before mjr_makeContext was called
```

**Comment by pseudo-rnd-thoughts** [comment]
@rodrigodelazcano Any ideas?

**Comment by rodrigodelazcano** [comment]
Hey @ygrayson can you try running it with `xvfb-run -a python your_script.py`? When rendering mujoco headless GLFW will look for a non existing display. You can generate a virtual display buffer with `xvfb` (`sudo apt install xvfb`)

**Comment by ygrayson** [comment]
Hii @rodrigodelazcano, thanks a lot for your reply! I have tested running this on my Windows Subsystem for Linux (WSL) (which is also headerless, and it worked perfectly. I will also test it on server once I get administrative access to install `xvfb`, but I think the result should be the same. Thanks 

<img src=https://user-images.githubusercontent.com/33047668/229378346-ebf8fd24-3c31-4705-a070-7e7e4e2a0e38.png width=300>

**Comment by ex3ndr** [comment]
Unfortunatelly, xvfb is not available in docker environments like paperspace.com. Any other work-arounds?

**Comment by mohammadtajdani** [comment]
Hello and respect,
I use MuJoCo and I want to run the code below in my Conda environment in VS Code. I have read all your comments, but I can't understand what you mean. Could you please explain in more detail how to solve this problem?
Note: I am using Ubuntu.
xml = """
<mujoco>
  <worldbody>
    <geom name="red_box" type="box" size=".2 .2 .2" rgba="1 0 0 1"/>
    <geom name="green_sphere" pos=".2 .2 .2" size=".1" rgba="0 1 0 1"/>
  </worldbody>
</mujoco>
"""
# Make model and data
model = mujoco.MjModel.from_xml_string(xml)
data = mujoco.MjData(model)

# Make renderer, render and show the pixels
with mujoco.Renderer(model) as renderer:
  media.show_image(renderer.render())

**Comment by Kallinteris-Andreas** [comment]
If you're using MuJoCo outside of gymnasium, Ask for help in the MuJoCo reposatory

**Comment by mohammadtajdani** [comment]
> If you're using MuJoCo outside of gymnasium, Ask for help in the MuJoCo reposatory

I appreciate it.
