### ISSUE TITLE
[Question] Weird TypeError occurs when trying to import gymnasium

### ISSUE THREAD

**Issue by DarthMalloc** [Farama-Foundation/Gymnasium#428]
### Question

I am trying to use the latest version of gymnasium with python 3.10.6 on Ubuntu 22.04. When I type `import gymnasium`, I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/idlelib/run.py", line 578, in runcode
    exec(code, self.locals)
  File "<pyshell#0>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/gymnasium/__init__.py", line 12, in <module>
    from gymnasium.envs.registration import make, spec, register, registry, pprint_registry
  File "/usr/local/lib/python3.10/dist-packages/gymnasium/envs/__init__.py", line 364, in <module>
    load_env_plugins()
  File "/usr/local/lib/python3.10/dist-packages/gymnasium/envs/registration.py", line 273, in load_env_plugins
    for plugin in metadata.entry_points(group=entry_point):
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1009, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1006, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 941, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```
I would greatly appreciate guidance on how to fix it.

**Comment by pseudo-rnd-thoughts** [comment]
Hey, this is a strange issue,
What is gymnasium version are you using? 
Could you add your `pip freeze`? 

Gymnasium and gym have some magic that loads other modules that register an entry point so there will be a conflict with another module most likely

**Comment by DarthMalloc** [comment]
Thanks for getting back to me so soon! This is the output from my `pip freeze`:
```
absl-py==1.2.0
ale-py==0.8.0
appdirs==1.4.4
apturl==0.5.2
astunparse==1.6.3
atari-py==0.2.9
attrs==22.1.0
autograd==1.4
autoray==0.3.2
bcrypt==3.2.0
blinker==1.4
box2d-py==2.3.5
Brlapi==0.8.3
cached-property==1.5.2
cachetools==5.2.0
certifi==2020.6.20
cffi==1.15.1
chardet==4.0.0
chex==0.1.6
click==8.0.3
cloudpickle==2.1.0
colorama==0.4.4
command-not-found==0.3
cryptography==3.4.8
cupshelpers==1.0
cycler==0.11.0
Cython==0.29.32
dbus-python==1.2.18
decorator==4.4.2
defer==1.0.6
dill==0.3.6
distro==1.7.0
distro-info===1.1build1
dm-tree==0.1.8
dopamine-rl==4.0.6
duplicity==0.8.21
etils==1.0.0
Farama-Notifications==0.0.4
fasteners==0.17.3
flatbuffers==23.1.21
flax==0.6.5
fonttools==4.37.1
future==0.18.2
gast==0.4.0
gin-config==0.5.0
glfw==2.5.4
google-auth==2.14.1
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.50.0
gym-minigrid==1.1.0
gym-notices==0.0.8
gymnasium==0.28.1
gymnasium-notices==0.0.1
h5py==3.7.0
httplib2==0.20.2
idna==3.3
imageio==2.21.1
imageio-ffmpeg==0.4.7
importlib-metadata==4.6.4
importlib-resources==5.9.0
iniconfig==1.1.1
jax==0.4.3
jax-jumpy==1.0.0
jaxlib==0.3.24
jeepney==0.7.1
keras==2.11.0
keyring==23.5.0
kiwisolver==1.4.4
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
libclang==15.0.6.1
lockfile==0.12.2
loguru==0.6.0
louis==3.20.0
lz4==4.0.2
macaroonbakery==1.3.1
Mako==1.1.3
Markdown==3.4.1
markdown-it-py==2.1.0
MarkupSafe==2.1.1
matplotlib==3.5.3
mdurl==0.1.2
Minigrid==2.1.0
monotonic==1.6
more-itertools==8.10.0
moviepy==1.0.3
mpmath==1.2.1
msgpack==1.0.4
msgpack-numpy==0.4.8
mujoco==2.3.1.post1
mujoco-py==2.1.2.14
multimethod==1.9
multiprocess==0.70.14
netifaces==0.11.0
networkx==2.8.6
ninja==1.10.2.3
ntlm-auth==1.5.0
numpy==1.23.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.2.0
olefile==0.46
opencv-python==4.6.0.66
opt-einsum==3.3.0
optax==0.1.4
orbax==0.1.1
packaging==21.3
pandas==1.5.3
paramiko==2.9.3
pathos==0.3.0
pbr==5.11.0
PennyLane==0.25.1
PennyLane-Lightning==0.25.1
pexpect==4.8.0
Pillow==9.0.1
pluggy==1.0.0
ply==3.11
pox==0.3.2
ppft==1.7.6.6
proglog==0.1.10
protobuf==3.12.4
psutil==5.9.4
ptyprocess==0.7.0
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.20.1
pycparser==2.21
pycups==2.0.1
pygame==2.1.3.dev8
Pygments==2.14.0
PyGObject==3.42.1
PyJWT==2.3.0
pylatexenc==2.10
pymacaroons==0.13.0
PyNaCl==1.5.0
PyOpenGL==3.1.6
pyparsing==2.4.7
pyRFC3339==1.1
pytest==7.0.1
python-apt==2.4.0+ubuntu1
python-dateutil==2.8.1
python-debian===0.1.43ubuntu1
pytz==2022.1
pyxdg==0.27
PyYAML==5.4.1
pyzmq==24.0.1
qiskit==0.39.2
qiskit-aer==0.11.1
qiskit-ibmq-provider==0.19.2
qiskit-terra==0.22.2
reportlab==3.6.8
requests==2.25.1
requests-ntlm==1.1.0
requests-oauthlib==1.3.1
retworkx==0.11.0
rich==13.3.1
rsa==4.9
scipy==1.9.1
screen-resolution-extra==0.0.0
SecretStorage==3.3.1
semantic-version==2.10.0
sentencepiece==0.1.97
Shimmy==0.2.0
six==1.16.0
stevedore==4.1.1
swig==4.0.2
symengine==0.9.2
sympy==1.11.1
systemd-python==234
tabulate==0.9.0
tensorboard==2.11.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.11.0
tensorflow-estimator==2.11.0
tensorflow-io-gcs-filesystem==0.30.0
tensorflow-probability==0.19.0
tensorpack==0.11
tensorstore==0.1.31
termcolor==2.1.1
tf-slim==1.1.0
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
torch==1.13.1
torchpack==0.3.1
torchquantum==0.1.5
torchtext==0.6.0
torchvision==0.14.0
tqdm==4.64.1
tweedledum==1.1.1
typing_extensions==4.3.0
ubuntu-advantage-tools==8001
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
usb-creator==0.3.7
wadllib==1.3.6
websocket-client==1.4.2
websockets==10.4
Werkzeug==2.2.2
wrapt==1.15.0rc1
xdg==5
xkit==0.0.0
zipp==1.0.0
```
Does this show where the conflict might be?

**Comment by pseudo-rnd-thoughts** [comment]
Im trying to work out what the issue and how to debug it but as the error originates in importlib
https://docs.python.org/3/library/importlib.metadata.html

Could you print all of the entry points?

**Comment by DarthMalloc** [comment]
I am not sure if I used the right code to get the entry points, since this is what I used
```
from importlib.metadata import *
eps = entry_points()
```
but the output that I got was
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/idlelib/run.py", line 578, in runcode
    exec(code, self.locals)
  File "<pyshell#1>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1009, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1006, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 941, in _normalized_name
    return self._name_from_stem(stem) or super()._normalized_name
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

```
This seems to be at the root of the problem. Is there another way to see the entry points?

**Comment by pseudo-rnd-thoughts** [comment]
Looking at the source code,  https://github.com/python/cpython/blob/5342f5e713e0cc45b6f226d2d053a8cde1b4d68e/Lib/importlib/metadata/__init__.py#L1020

Could you print the `list(importlib.metadata.Distributions())` and `itertools.chain.from_iterable(dist.entry_points for dist in distributions())`?

**Comment by DarthMalloc** [comment]
Thanks again for getting back to me so soon!
When I do
```
import importlib
list(importlib.metadata.Distributions())
```
I get
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/idlelib/run.py", line 578, in runcode
    exec(code, self.locals)
  File "<pyshell#1>", line 1, in <module>
AttributeError: module 'importlib' has no attribute 'metadata'
```
and when I run 
```
import itertools
from importlib.metadata import distributions
itertools.chain.from_iterable(dist.entry_points for dist in distributions())
```
I get
```
<itertools.chain object at 0x7f3e4eb250f0>
```

For the first one, did you mean `Distribution()`?

**Comment by pseudo-rnd-thoughts** [comment]
You will need to do `import importlib.metadata`

For the second part, you will need to surround it by a `list()` to extract all of the elements of the generator

**Comment by pseudo-rnd-thoughts** [comment]
Looking through the `SelectableGroups.load` function (https://github.com/python/cpython/blob/5342f5e713e0cc45b6f226d2d053a8cde1b4d68e/Lib/importlib/metadata/__init__.py#L467)

The issue is with one of the `group` values not being a str or byte like
```python

import itertools
import importlib.metadata as mt

for entry_point in itertools.chain.from_iterable(dist.entry_points for dist in mt.distributions()):
     group = entry_point.group
     try:
          normalized_name = re.sub(r"[-_.]+", "-", group).lower().replace('-', '_')
     except TypeError as e:
           print(entry_point)
           print(e)
```
Try this

**Comment by DarthMalloc** [comment]
Is there a way to check the entry point group for a package by name and see if that is package that is causing the problem?

**Comment by pseudo-rnd-thoughts** [comment]
Could you confirm the suspect error and you can replicate it with the following code. `eps` is `itertools.chain.from_iterable(dist.entry_points for dist in mt.distributions())`.
```python
by_group = operator.attrgetter('group')
ordered = sorted(eps, key=by_group)
```

Then if you compute the key value for each element, see if that raises the error

**Comment by DarthMalloc** [comment]
Thanks! Just to make sure I'm doing this correctly, what's the import for `operator`?

**Comment by pseudo-rnd-thoughts** [comment]
`import operator` I believe

**Comment by DarthMalloc** [comment]
Right now I think I might go the route of removing my python3.10 installation and rebuilding the ecosystem from scratch. Would that be a safe and viable approach? In particular, would it get rid of the files that are causing the problem?

**Comment by pseudo-rnd-thoughts** [comment]
I just realised that I got this wrong on where the error is

```python
import importlib.metadata as mt
import operator

key = operator.attrgetter('_normalized_name')
for distribution in mt.distributions():
    print(distribution)  # distribution.name
    print(key(distribution))
```

If this does produce the error, could you use `distribution.name` to see the actual name of the distributor with the issue

**Comment by DarthMalloc** [comment]
Thanks! I actually manage to fix the issue by installing python3.11 and continuing on with that, but I will keep this in mind if I encounter this issue again. In the meantime, I should probably let the Kubernetes devs know that Kubernetes has a conflict with Gymnasium.
