### ISSUE TITLE
[Bug Report] TypeError: 'NoneType' object is not callable in /mujoco_rendering.py in `free`

### ISSUE THREAD

**Issue by sonelu** [Farama-Foundation/Gymnasium#438]
### Describe the bug

When closing an environment that used `env.render()` the following dump is issued:

```
Exception ignored in: <function WindowViewer.__del__ at 0x7fcc0d2530e0>
Traceback (most recent call last):
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 335, in __del__
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 330, in free
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/glfw/__init__.py", line 1274, in destroy_window
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/glfw/__init__.py", line 687, in errcheck
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/glfw/__init__.py", line 70, in _reraise
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/glfw/__init__.py", line 666, in callback_wrapper
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/glfw/__init__.py", line 912, in _handle_glfw_errors
TypeError: 'NoneType' object is not callable
```

https://github.com/Farama-Foundation/Gymnasium/blob/3923e35a18b5e1c1936ce5878c10f49a3cc94ed3/gymnasium/envs/mujoco/mujoco_rendering.py#L326-331

```python
    def free(self):
        if self.window:
            if glfw.get_current_context() == self.window:
                glfw.make_context_current(None)
        glfw.destroy_window(self.window)
        self.window = None
```

Changing the code to this seems to remove the error:

```python
    def free(self):
        if self.window:
            if glfw.get_current_context() == self.window:
                glfw.make_context_current(None)
            glfw.destroy_window(self.window)
            self.window = None
```

### System info

Describe how Gymnasium was installed: pip 
Version of gymnasium:  0.28.1
What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it.: 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 22.04 under WSL2)
Python version: 3.7.12

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks @sonelu, could you make a PR to add your change

**Comment by Kallinteris-Andreas** [comment]
I can not replicate @sonelu show me the steps to replicate

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas Are you using windows wsl?

**Comment by Kallinteris-Andreas** [comment]
@pseudo-rnd-thoughts no i run arch

**Comment by sonelu** [comment]
Code:

```python
import gymnasium as gym

env = gym.make('Humanoid-v4', render_mode='human')

env.reset()

for _ in range(100):
    action = env.action_space.sample()
    obs, rew, term, trunc, info =  env.step(action)
    env.render()
    if term or trunc:
        env.reset()

env.close()
```


Dump
```log
(sb3) ml@Alex4:~/Learning/sacv$ python render.py
Exception ignored in: <function WindowViewer.__del__ at 0x7ffafaa9f290>
Traceback (most recent call last):
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 335, in __del__
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 330, in free
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/glfw/__init__.py", line 1274, in destroy_window
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/glfw/__init__.py", line 687, in errcheck
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/glfw/__init__.py", line 70, in _reraise
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/glfw/__init__.py", line 666, in callback_wrapper
  File "/home/ml/mambaforge-pypy3/envs/sb3/lib/python3.7/site-packages/glfw/__init__.py", line 912, in _handle_glfw_errors
TypeError: 'NoneType' object is not callable
```

**Comment by Kallinteris-Andreas** [comment]
Thanks, I can replicate now, bug is only present with `render_mode='human'` (which was not stated in the initial post)
