### ISSUE TITLE
[Bug Report] TypeError: entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by 1412kauti** [Farama-Foundation/Gymnasium#442]
### Describe the bug

I got this error while importing Gymnasium.

I have tried both installing from pip and from source.

### Code example

```shell
>>> import gymnasium
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaito/Documents/Expt/Gymnasium/gymnasium/__init__.py", line 12, in <module>
    from gymnasium.envs.registration import (
  File "/home/kaito/Documents/Expt/Gymnasium/gymnasium/envs/__init__.py", line 382, in <module>
    load_plugin_envs()
  File "/home/kaito/Documents/Expt/Gymnasium/gymnasium/envs/registration.py", line 565, in load_plugin_envs
    for plugin in metadata.entry_points(group=entry_point):
TypeError: entry_points() got an unexpected keyword argument 'group'

```
```


### System info


             /////////////
         /////////////////////            kaito@comet 
      ///////*767////////////////         ----------- 
    //////7676767676*//////////////       OS: Pop!_OS 20.04 LTS x86_64 
   /////76767//7676767//////////////      Host: B550I AORUS PRO AX 
  /////767676///*76767///////////////     Kernel: 6.0.12-76060012-generic 
 ///////767676///76767.///7676*///////    Uptime: 1 day, 12 hours, 30 mins 
/////////767676//76767///767676////////   Packages: 3035 (dpkg), 13 (flatpak), 6 (snap) 
//////////76767676767////76767/////////   Shell: bash 5.0.17 
///////////76767676//////7676//////////   Resolution: 1080x1920, 1920x1080 
////////////,7676,///////767///////////   DE: GNOME 
/////////////*7676///////76////////////   WM: Mutter 
///////////////7676////////////////////   WM Theme: Pop 
 ///////////////7676///767////////////    Theme: ChromeOS-Dark [GTK2/3] 
  //////////////////////'////////////     Icons: candy-icons [GTK2/3] 
   //////.7676767676767676767,//////      Terminal: guake 
    /////767676767676767676767/////       CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
      ///////////////////////////         GPU: NVIDIA 07:00.0 NVIDIA Corporation Device 2504 
         /////////////////////            Memory: 10259MiB / 32002MiB 
             /////////////
                                                                  
                                                                  


```
python == 3.7.16 (conda)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Could you run `pip install --upgrade importlib_metadata`
