### ISSUE TITLE
[Bug Report] Minor inconsistency with `Tuple` and `MultiDiscrete` spaces

### ISSUE THREAD

**Issue by Rohan138** [Farama-Foundation/Gymnasium#457]
### Describe the bug

`Tuple` and `MultiDiscrete` spaces with the same shape return `True` for each other's inputs, but `gym.utils.flatten(md, tup.sample())` fails.

Ideally, I think if we're converting between `tuple` and `np.ndarray` in the `contains` function ([Link](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/spaces/multi_discrete.py#L133), [Link](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/spaces/tuple.py#L116)), we should also do it in the `gym.spaces.utils.flatten` dispatch for both spaces ([Link](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/spaces/utils.py#L175), [Link](https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/spaces/utils.py#L185)); or both of them should fail in `contains`.

Found this while debugging an RLlib issue, but the current behavior makes it hard to track down why `utils.flatten` is failing for my use case.

### Code example

```shell
import gymnasium as gym
tup = gym.spaces.Tuple((gym.spaces.Discrete(2), gym.spaces.Discrete(5)))
md = gym.spaces.MultiDiscrete((2, 5))
# Contains
tup.contains(md.sample())
md.contains(tup.sample())
# Flatten
gym.spaces.utils.flatten(tup, md.sample())
gym.spaces.utils.flatten(md, tup.sample())
###
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/gymnasium/spaces/utils.py", line 157, in _flatten_multidiscrete
    onehot[offsets[:-1] + x.flatten()] = 1
AttributeError: 'tuple' object has no attribute 'flatten'
```

### System info

gymnasium 0.26.3

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the bug report, to some degree there is some luck here that samples from one space might be accepted with another space while not-truly being part of the second space. 

I see two options to solve this
1. Make `MultiDiscrete.contains` more strict - The problem is partially that `contains` accepts tuples which should never be sampled from the space. The possible issue is backward compatibility, but we can justify this as a bug fix
2. Make `flatten(MultiDiscrete, sample)` cast all samples to a `np.array` first before we do more operations

I would suggest the first option, @Rohan138 any thoughts?
