### ISSUE TITLE
[Bug Report] Old API compatibility - render and FlattenObservation

### ISSUE THREAD

**Issue by ronTohar1** [Farama-Foundation/Gymnasium#461]
### Describe the bug

I guess its a bug? 
(using a custom environment)
I had an environment that is old API compatible (e.g reset returns just obs instead of obs,{} etc...), and registered through gym of course.
In order to work with gymnasium I just used the EnvCompatibility wrapper to wrap my environment.
As it seems, the spaces in the environment (action space and observation space) are still instances of gym.spaces.Space and not gymnasium.spaces.Space, and thereofre, when tried to flatten them with FlattenObservation, it showed the following error: 

`Traceback (most recent call last):
  File "c:\Users\Ron Tohar\Desktop\Teza\Battleships\BattleshiPs\train.py", line 38, in <module>
    game_loop()
  File "c:\Users\Ron Tohar\Desktop\Teza\Battleships\BattleshiPs\train.py", line 26, in game_loop
    env = FlattenObservation(env)
  File "C:\Users\Ron Tohar\Desktop\Teza\Battleships\BattleshiPs\.venv\lib\site-packages\gymnasium\wrappers\flatten_observation.py", line 32, in __init__
    self.observation_space = spaces.flatten_space(env.observation_space)
  File "C:\Program Files\Python310\lib\functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\Ron Tohar\Desktop\Teza\Battleships\BattleshiPs\.venv\lib\site-packages\gymnasium\spaces\utils.py", 
line 463, in flatten_space
    raise NotImplementedError(f"Unknown space: "{space}" ")
NotImplementedError: Unknown space: "Box(0, 1, (2, 10, 10), int32)"`

Explaination for why I wanted to use FlattenObservation:
In order to train with the DQN model of stable-baselines3 for example, they dont allow to Tuple space, which I needed to use. Therefore, I wanted to flatten the observation space so it would fit it as a box.

if your answer is "just migrate the environment code":
I feel like there should be an example of full environment migrating in the gymnasium documentation as it was very much missing.
If I just work as you mentioned in the migrating section + blog post about gymnasium, I replaced all `import gym` with `importy gymnasium as gym` and every import such as `from gym import ....` to `from gymnasium import ....` and also registered it to gymnasium of course instead of gym.
Then, when using the EnvCompatibility, the render method doesnt work at all for some reason, and the following error is shown:
`Traceback (most recent call last):
  File "c:\Users\Ron Tohar\Desktop\Teza\Battleships\BattleshiPs\train.py", line 39, in <module>
    game_loop()
  File "c:\Users\Ron Tohar\Desktop\Teza\Battleships\BattleshiPs\train.py", line 34, in game_loop
    env.render()
  File "C:\Users\Ron Tohar\Desktop\Teza\Battleships\BattleshiPs\.venv\lib\site-packages\gymnasium\core.py", line 418, in render
    return self.env.render()
  File "C:\Users\Ron Tohar\Desktop\Teza\Battleships\BattleshiPs\.venv\lib\site-packages\gymnasium\wrappers\compatibility.py", line 124, in render
    return self.env.render(mode=self.render_mode)
  File "C:\Users\Ron Tohar\Desktop\Teza\Battleships\BattleshiPs\.venv\lib\site-packages\gymnasium\wrappers\order_enforcing.py", line 70, in render
    return self.env.render(*args, **kwargs)
  File "C:\Users\Ron Tohar\Desktop\Teza\Battleships\BattleshiPs\.venv\lib\site-packages\gymnasium\wrappers\env_checker.py", line 63, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
TypeError: env_render_passive_checker() got an unexpected keyword argument 'mode'`

So there are actually 2 bugs here.
Thanks in advance

### Code example

```shell
from stable_baselines3.dqn import DQN
import gym_battleship # environment created by https://github.com/thomashirtz/gym-battleship
import gymnasium
import gym
from gymnasium.wrappers.flatten_observation import FlattenObservation
from gymnasium.wrappers.compatibility import EnvCompatibility

env = gym.make("Battleship-v0")
env = EnvCompatibility(env)
env = FlattenObservation(env)
obs = env.reset()
done = False
while not done:
        action = env.action_space.sample()
        obs, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated
        env.render()
```

### System info

- installed gymnasium using pip
- gymnasium 0.28.1
- Windows 10 OS
- python version 3.10.11

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by ronTohar1** [comment]
Thank you very much for the detailed answer. I now understand much more than what I was able to using the documentation only, as it misses some basic explanation of some of the new concepts, preferably using examples. 
Amazing work btw.
