### ISSUE TITLE
[Question] AttributeError: 'NoneType' object has no attribute 'glfwGetCurrentContext'

### ISSUE THREAD

**Issue by zichunxx** [Farama-Foundation/Gymnasium#472]
### Question

Hi! 

I'm learning how to use `gymnasium` and encounter the following error:

```
Exception ignored in: <function WindowViewer.__del__ at 0x7effa4dad560>
Traceback (most recent call last):
  File "/home/rlc/mambaforge/envs/tianshou/lib/python3.7/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 335, in __del__
  File "/home/rlc/mambaforge/envs/tianshou/lib/python3.7/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 328, in free
  File "/home/rlc/mambaforge/envs/tianshou/lib/python3.7/site-packages/glfw/__init__.py", line 2366, in get_current_context
AttributeError: 'NoneType' object has no attribute 'glfwGetCurrentContext'
```

The Mujoco window flashes and then disappears. Here is the minimum code snippet to reproduce the error
```
import gymnasium as gym

env=gym.make('Humanoid-v4', render_mode='human')
obs=env.reset()
env.render()
```

```
Gymnasium: 0.28.1
glfw: 2.5.9
```

Thanks!

**Comment by Kallinteris-Andreas** [comment]
0)`env.render()` is not thread locking 

try:
```python
import gymnasium as gym

env=gym.make('Humanoid-v4', render_mode='human')
obs=env.reset()
env.render()
breakpoint()
```

1)That error message will be fixed in the next version
