### ISSUE TITLE
[Question] Environment `SurroundNoFrameskip` doesn't exist

### ISSUE THREAD

**Issue by edbeeching** [Farama-Foundation/Gymnasium#592]
### Question

The Atari env Surround, does not appear to exist in gymnasium, any idea why?

```
import gymnasium as gym
env = gym.make("SurroundNoFrameskip-v4")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edward/work/sample-factory/venv/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 740, in make
    env_spec = _find_spec(id)
  File "/home/edward/work/sample-factory/venv/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 537, in _find_spec
    _check_version_exists(ns, name, version)
  File "/home/edward/work/sample-factory/venv/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 403, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/edward/work/sample-factory/venv/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 380, in _check_name_exists
    raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment `SurroundNoFrameskip` doesn't exist. Did you mean: `PongNoFrameskip`?
```

**Comment by pseudo-rnd-thoughts** [comment]
Surround is only available as v5, https://gymnasium.farama.org/main/environments/atari/surround/
