### ISSUE TITLE
[Bug Report] spaces.Box ValueError: Some low values are greater than high

### ISSUE THREAD

**Issue by elliottower** [Farama-Foundation/Gymnasium#617]
### Describe the bug

Found when testing python 3.11 with other farama projects (supersuit in this case), but just tested with a new venv and gymnasium v29 and python3.11 and nothing else

https://github.com/Farama-Foundation/SuperSuit/actions/runs/5583348225/jobs/10203570526

### Code example

```shell
from gymnasium import spaces
import numpy as np
spaces.Box(low=0, high=255, shape=[64, 64, 3], dtype=np.int8)
```

```
Traceback (most recent call last):
  File "/home/elliot/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/elliot/anaconda3/envs/shimmy/lib/python3.11/site-packages/gymnasium/spaces/box.py", line 126, in __init__
    raise ValueError(
ValueError: Some low values are greater than high, low=[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]
 ...
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], high=[[[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  ...
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]
 [[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  ...
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]
 [[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  ...
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]
 ...
 [[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  ...
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]
 [[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  ...
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]
 [[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]
  ...
  [-1 -1 -1]
  [-1 -1 -1]
  [-1 -1 -1]]]
```
```


### System info

_No response_

### Additional context

_No response_

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by elliottower** [comment]
Oh it looks like this is just a poorly designed SuperSuit test cause they use np.int8 when it's a number larger than +-128

**Comment by pseudo-rnd-thoughts** [comment]
@elliottower I suspect it is meant to be `uint8` as this would be a valid bound

**Comment by elliottower** [comment]
> @elliottower I suspect it is meant to be `uint8` as this would be a valid bound

Ya makes sense just not int8
