### ISSUE TITLE
[Bug Report] AsyncVectorEnv works until end of episode then multiprocessing is None: AttributeError: 'NoneType' object has no attribute 'TimeoutError'

### ISSUE THREAD

**Issue by sebnapi** [Farama-Foundation/Gymnasium#722]
### Describe the bug

Running the AsyncVectorEnv works until the end of the episode, then I run into a **strange** Error:

```
Exception ignored in: <function AsyncVectorEnv.__del__ at 0x00000290CE89D1F0>
Traceback (most recent call last):
  File "...\site-packages\gymnasium\vector\async_vector_env.py", line 549, in __del__
  File ...\site-packages\gymnasium\vector\vector_env.py", line 272, in close
  File "...\lib\site-packages\gymnasium\vector\async_vector_env.py", line 465, in close_extras
AttributeError: 'NoneType' object has no attribute 'TimeoutError'
```

This is the code in question, line 465 makes a call to `mp.TimeoutError`:

https://github.com/Farama-Foundation/Gymnasium/blob/baf78078c35ca45f12db270c3b3f79491bed84f4/gymnasium/vector/async_vector_env.py#L443-L468

It seems as if mp is None. When setting a breakpoint on the Line 3 of the file, just after the multiprocessing import, I can confirm that multiprocessing has the TimeoutError class available. As I say all the rest works fine, just at the end this happens. I can't set a breakpoint in the function as this results in a Exception regarding PyCharm, probably due to the nature of multiprocessing.

### Code example

```shell
import gymnasium as gym
from multiprocessing import freeze_support

if __name__ == "__main__":
    freeze_support()

    validation_envs = gym.vector.AsyncVectorEnv([lambda: make_env("dataset.pkl") for _ in range(5)])
    agent = load_agent("trained/agent.pkl")
    evaluation() # runs getting observations, pick_actions, step() etc.
```

### System info

OS: Windows 10.0.19045
Python: 3.9.17 (main, Jul  5 2023, 20:47:11) [MSC v.1916 64 bit (AMD64)]
gymnasium.__version__ == 0.29.1

miniconda environment: conda 23.5.2

I would be happy to use WSL but PyCharm Community does not allow me to debug the code (remotely), therefore I'm bound to use the Windows environment.

### Additional context

The agent was trained on `SyncVectorEnv`, I was just working on parallelizing the training, so I started with a simple evaluation.

I tried to google it but I found nothing helpful. Besides this maybe: https://github.com/openai/gym/issues/3191

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by sebnapi** [comment]
I was able to fix it, by moving everything from the `__main__` method to a function and calling the function in `__main__`, what also may help is running another file as `__main__` and importing the function to run from a different file, see:

https://discuss.python.org/t/why-does-multiprocessing-not-work-properly-in-main-py/20822/2

> 
> When a script is run directly, __name__ is set to __main__, whereas when that same script is imported __name__ is set to the script’s name minus the extension. Therefore, if you name the script __main__, there’s no way it can tell whether it was called directly or imported.
> 
> The multiprocessing module imports the script in the subprocesses it starts, so any initialisation that should be done only in the main script and not in the subprocesses should be protected by the if __name__ == '__main__': idiom. Naming the script __main__ will lead the subprocesses to think they are the main process and should start new subprocesses.
