### ISSUE TITLE
[Bug Report] Environment not resetting at termination.

### ISSUE THREAD

**Issue by psymbio** [Farama-Foundation/Gymnasium#796]
### Describe the bug

The environment not resetting when the termination condition is True.

### Code example

```shell
import numpy as np
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3.common.env_checker import check_env

ARRAY = np.linspace(0, 10)
TOTAL_DAYS = len(ARRAY)
N_DISCRETE_ACTIONS = 1

class NewEnv(gym.Env):
    metadata = {"render_modes": ["human"], "render_fps": 30}

    def __init__(self):
        super().__init__()
        # Define action and observation space
        # They must be gym.spaces objects
        # Example when using discrete actions:
        self.action_space = spaces.Discrete(N_DISCRETE_ACTIONS)
        # Example for using image as input (channel-first; channel-last also works):
        self.observation_space = spaces.Box(low=0, high=1,
                                            shape=(1,), dtype=np.float64)

    def step(self, action):
        if action == 1:
            pass
        observation = [ARRAY[self.ith_day]]
        observation = np.array(observation)

        self.ith_day += 1
        if self.ith_day >= TOTAL_DAYS - 1:
            self.terminated = True
            print("\n\nTERMINATION REACHED: ", self.ith_day)
        
        info = {}
        self.reward = 1

        return observation, self.reward, self.terminated, self.truncated, info

    def reset(self, seed=None, options=None):
        super().reset(seed=seed, options=options)
        self.ith_day = 0
        self.truncated = False
        self.terminated = False
        self.reward = 0

        observation = [1]
        observation = np.array(observation)
        info = {}
        return observation, info


env = NewEnv()
check_env(env)

env = NewEnv()
episodes = 10
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0
    while not done:
        action = env.action_space.sample()
        n_state, reward, terminated, truncated, info = env.step(action)
        print(n_state[0], end='\t')
        score += reward
    print(f'Episode: {episode}, Score: {score}')
    env.render()
```

Error log:
```bash
TERMINATION REACHED:  49
9.795918367346939

TERMINATION REACHED:  50
10.0    Traceback (most recent call last):
  File "/home/vanilla_skies/projects/sbp/sir_submission/clean_code/04_environment_issue.py", line 63, in <module>
    n_state, reward, terminated, truncated, info = env.step(action)
  File "/home/vanilla_skies/projects/sbp/sir_submission/clean_code/04_environment_issue.py", line 26, in step
    observation = [ARRAY[self.ith_day]]
IndexError: index 50 is out of bounds for axis 0 with size 50
```

### System info

Gymnasium was installed using: pip
Version of Gymnasium: 0.29.1
OS: Ubuntu 20.04.5 LTS on WSL2
Python version: Python 3.9.7

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
Your `done` variable is constantly `False`

**Comment by psymbio** [comment]
Ah, thanks - I think I missed that while shifting to this version.
